name: Manual Add Node

on:
  workflow_dispatch:
    inputs:
      fullName:
        description: 'Full name'
        required: true
      year:
        description: 'Year (YYYY)'
        required: true
      website:
        description: 'Website URL'
        required: true
      interest_1:
        description: 'Primary interest'
        required: true
        type: choice
        options: &Interests
          - UX/UI
          - UXR
          - Graphic
          - Brand
          - Frontend
          - Backend
          - Full Stack
          - AI/ML
          - Quant
          - QA
          - Game Dev
          - SRE
          - Product
          - Project
          - Program
          - CAD/Simulation
          - Manufacturing
          - Materials
          - Automotive
          - Aero
          - Embedded
          - Signals
          - Sensors
          - Robotics
          - Power Systems
          - Communications
          - Data
          - Business
          - VC
          - IDK Yet!
          - Other
      interest_2:
        description: 'Secondary interest'
        required: true
        type: choice
        options: *Interest
      interest_3:
        description: 'Tertiary interest'
        required: true
        type: choice
        options: *Interest
      bio:
        description: 'Bio (optional)'
        required: false

jobs:
  add-node:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate data file exists
        run: |
          if [ ! -f public/data.json ]; then
            echo "Data file not found at public/data.json"
            exit 1
          fi

      - name: Append node to public/data.json
        id: append
        shell: bash
        run: |
          set -euo pipefail

          FULL_NAME="${{ github.event.inputs.fullName }}"
          YEAR="${{ github.event.inputs.year }}"
          WEBSITE="${{ github.event.inputs.website }}"
          INTEREST_1="${{ github.event.inputs.interest_1 }}"
          INTEREST_2="${{ github.event.inputs.interest_2 }}"
          INTEREST_3="${{ github.event.inputs.interest_3 }}"
          BIO="${{ github.event.inputs.bio }}"

          # Compute next id = max(tonumber(id)) + 1 (handles string ids too)
          NEXT_ID="$(jq -r '([.nodes[].id | tonumber] | (max? // 0)) + 1' public/data.json)"

          # Guard that NEXT_ID is numeric
          case "$NEXT_ID" in (''|*[!0-9]*) echo "Bad NEXT_ID: $NEXT_ID"; exit 1;; esac

          # Warn if YEAR isn't 4 digits; we'll coerce to null
          if ! printf '%s\n' "$YEAR" | grep -Eq '^[0-9]{4}$'; then
            echo "Warning: YEAR \"$YEAR\" is not a 4-digit number; setting year=null in JSON."
          fi

          # Build new node JSON (cast inside jq)
          NEW_NODE="$(jq -n \
            --arg id "$NEXT_ID" \
            --arg fullName "$FULL_NAME" \
            --arg year "$YEAR" \
            --arg website "$WEBSITE" \
            --arg interest_1 "$INTEREST_1" \
            --arg interest_2 "$INTEREST_2" \
            --arg interest_3 "$INTEREST_3" \
            --arg bio "${BIO:-}" \
            '{
              id: ($id|tonumber),
              fullName: $fullName,
              year: (try ($year|tonumber) catch null),
              website: ($website|tostring),
              interests: { interest_1: $interest_1, interest_2: $interest_2, interest_3: $interest_3 },
              bio: $bio
            }'
          )"

          # Append to public/data.json
          TMP="$(mktemp)"
          jq --argjson newNode "$NEW_NODE" '.nodes += [$newNode]' public/data.json > "$TMP"
          mv "$TMP" public/data.json

          # Expose outputs for later steps
          {
            echo "new_node_json<<EOF"
            echo "$NEW_NODE"
            echo "EOF"
            echo "next_id=$NEXT_ID"
          } >> "$GITHUB_OUTPUT"

          # Optional debug: show last node
          jq -r '.nodes[-1]' public/data.json

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Add ${{ github.event.inputs.fullName }} (${{ github.event.inputs.year }})"
          body: |
            Auto-generated from manual workflow_dispatch.

            **New node:**
            ```json
            ${{ steps.append.outputs.new_node_json }}
            ```
          base: main
          # Let the action create & push this branch; it doesn't need to exist beforehand.
          branch: add/node-${{ steps.append.outputs.next_id }}-${{ github.run_id }}
          delete-branch: true
