name: Manual Add Node

on:
  workflow_dispatch:
    inputs:
      fullName:
        description: 'Full name'
        required: true
      year:
        description: 'Year (YYYY)'
        required: true
      website:
        description: 'Website URL'
        required: true
      skill1:
        description: 'Primary skill'
        required: true
        type: choice
        options: &skills
          - UX/UI
          - UXR
          - Graphic
          - Brand
          - Frontend
          - Backend
          - Full Stack
          - AI/ML
          - Quant
          - QA
          - Game Dev
          - SRE
          - Product
          - Project
          - Program
          - CAD/Simulation
          - Manufacturing
          - Materials
          - Automotive
          - Aero
          - Embedded
          - Signals
          - Sensors
          - Robotics
          - Power Systems
          - Communications
          - Data
          - Business
          - VC
          - IDK Yet!
          - Other
      skill2:
        description: 'Secondary skill'
        required: true
        type: choice
        options: *skills
      skill3:
        description: 'Tertiary skill'
        required: true
        type: choice
        options: *skills
      bio:
        description: 'Bio (optional)'
        required: false

jobs:
  add-node:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.name "webring-bot"
          git config --global user.email "webring-bot@users.noreply.github.com"

      - name: Validate data file exists
        run: |
          test -f public/data.json || { echo "Data file not found at public/data.json"; exit 1; }

      - name: Append node to public/data.json
        id: append
        run: |
          set -euo pipefail
          FULL_NAME="${{ github.event.inputs.fullName }}"
          YEAR="${{ github.event.inputs.year }}"
          WEBSITE="${{ github.event.inputs.website }}"
          SKILL1="${{ github.event.inputs.skill1 }}"
          SKILL2="${{ github.event.inputs.skill2 }}"
          SKILL3="${{ github.event.inputs.skill3 }}"
          BIO="${{ github.event.inputs.bio }}"

          NEXT_ID="$(jq -r '([.nodes[].id | tonumber] | (max? // 0)) + 1' public/data.json)"

          NEW_NODE="$(jq -n \
            --arg id "$NEXT_ID" \
            --arg fullName "$FULL_NAME" \
            --arg year "$YEAR" \
            --arg website "$WEBSITE" \
            --arg skill1 "$SKILL1" \
            --arg skill2 "$SKILL2" \
            --arg skill3 "$SKILL3" \
            --arg bio "${BIO:-}" \
            '{
              id: ($id|tonumber),
              fullName: $fullName,
              year: (try ($year|tonumber) catch null),
              website: ($website|tostring),
              skills: { skill1: $skill1, skill2: $skill2, skill3: $skill3 },
              bio: $bio
            }'
          )"

          TMP="$(mktemp)"
          jq --argjson newNode "$NEW_NODE" '.nodes += [$newNode]' public/data.json > "$TMP"
          mv "$TMP" public/data.json

          {
            echo "new_node_json<<EOF"
            echo "$NEW_NODE"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: add/${{ github.run_id }}  # action will create/manage this
          title: "Add ${{ github.event.inputs.fullName }} (${{ github.event.inputs.year }})"
          commit-message: "feat: add ${{ github.event.inputs.fullName }} (${{ github.event.inputs.year }})"
          body: |
            Auto-generated from manual workflow_dispatch.

            **New node:**
            ```json
            ${{ steps.append.outputs.new_node_json }}
            ```
          add-paths: |
            public/data.json

      - name: Show PR link
        if: steps.cpr.outputs.pull-request-url
        run: echo "PR opened: ${{ steps.cpr.outputs['pull-request-url'] }}"
