name: Manual Add Node

on:
  workflow_dispatch:
    inputs:
      fullName:
        description: 'Full name'
        required: true
      year:
        description: 'Year (YYYY)'
        required: true
      website:
        description: 'Website URL'
        required: true
      skill1:
        description: 'Primary skill'
        required: true
        type: choice
        options: &skills
          - UX/UI
          - UXR
          - Graphic
          - Brand
          - Frontend
          - Backend
          - Full Stack
          - AI/ML
          - Quant
          - QA
          - Game Dev
          - SRE
          - Product
          - Project
          - Program
          - CAD/Simulation
          - Manufacturing
          - Materials
          - Automotive
          - Aero
          - Embedded
          - Signals
          - Sensors
          - Robotics
          - Power Systems
          - Communications
          - Data
          - Business
          - VC
          - IDK Yet!
          - Other
      skill2:
        description: 'Secondary skill'
        required: true
        type: choice
        options: *skills
      skill3:
        description: 'Tertiary skill'
        required: true
        type: choice
        options: *skills
      bio:
        description: 'Bio (optional)'
        required: false

jobs:
  add-node:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Append node and open PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const DATA_PATH = 'public/data.json';
            const BASE_BRANCH = 'main';

            const {
              fullName,
              year,
              website,
              skill1,
              skill2,
              skill3,
              bio
            } = inputs;

            const dataPath = path.join(process.cwd(), DATA_PATH);
            const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

            const nextId = data.nodes.length
              ? Math.max(...data.nodes.map(n => Number(n.id) || 0)) + 1
              : 1;

            const newNode = {
              id: nextId,
              fullName,
              year: parseInt(year, 10),
              website: website.trim(),
              skills: { skill1, skill2, skill3 },
              bio: bio || ''
            };

            data.nodes.push(newNode);

            const updated = JSON.stringify(data, null, 2) + '\n';
            fs.writeFileSync(dataPath, updated);

            const branch = `add/${fullName.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${Date.now()}`;

            const { data: base } = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: BASE_BRANCH
            });

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/${branch}`,
              sha: base.commit.sha
            });

            const { data: fileData } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: DATA_PATH,
              ref: BASE_BRANCH
            });

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: DATA_PATH,
              message: `feat: add ${fullName} to webring`,
              content: Buffer.from(updated, 'utf8').toString('base64'),
              branch,
              sha: Array.isArray(fileData) ? undefined : fileData.sha
            });

            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base: BASE_BRANCH,
              title: `Add ${fullName} (${year})`,
              body: [
                'Auto-generated from manual workflow_dispatch.',
                '',
                '```json',
                JSON.stringify(newNode, null, 2),
                '```'
              ].join('\n')
            });

            console.log(`✅ Pull Request #${pr.data.number} created: ${pr.data.html_url}`);
