name: Manual Add Node

on:
  workflow_dispatch:
    inputs:
      fullName:
        description: 'Full name'
        required: true
      year:
        description: 'Year (YYYY)'
        required: true
      website:
        description: 'Website URL'
        required: true
      david_selection:
        description: 'David selection (optional)'
        required: false
        default: ''
        type: choice
        options:
          - 'None'
          - 'David'
          - 'David + 1'
          - 'David + 2'
          - 'David + 3'
      skill1:
        description: 'Primary skill'
        required: true
      skill2:
        description: 'Secondary skill'
        required: true
      skill3:
        description: 'Tertiary skill'
        required: true
      bio:
        description: 'Bio (optional)'
        required: false

jobs:
  add-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Add node to JSON
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const DATA_PATH = 'public/data.json';
            const BASE_BRANCH = 'main';

            const {
              fullName,
              year,
              website,
              skill1,
              skill2,
              skill3,
              bio
            } = inputs;

            const newNode = {
              id: Date.now(), // or use nextId logic
              fullName,
              year: parseInt(year, 10),
              website,
              skills: { skill1, skill2, skill3 },
              bio: bio || ''
            };

            const dataPath = path.join(process.cwd(), DATA_PATH);
            const json = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

            json.nodes.push(newNode);
            json.nodes.sort((a, b) => a.fullName.localeCompare(b.fullName));
            const updated = JSON.stringify(json, null, 2) + '\n';

            fs.writeFileSync(dataPath, updated);

            const branch = `add/${fullName.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${Date.now()}`;

            const { data: base } = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: BASE_BRANCH
            });

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/${branch}`,
              sha: base.commit.sha
            });

            const { data: fileData } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: DATA_PATH,
              ref: BASE_BRANCH
            });

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: DATA_PATH,
              message: `feat: add ${fullName} to webring`,
              content: Buffer.from(updated, 'utf8').toString('base64'),
              branch,
              sha: Array.isArray(fileData) ? undefined : fileData.sha
            });

            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base: BASE_BRANCH,
              title: `Add ${fullName} (${year})`,
              body: 'Auto-generated via workflow_dispatch'
            });
