name: Manual Add Node

on:
  workflow_dispatch:
    inputs:
      fullName:
        description: 'Full name'
        required: true
      year:
        description: 'Year (YYYY)'
        required: true
      website:
        description: 'Website URL'
        required: true
      skill1:
        description: 'Primary skill'
        required: true
        type: choice
        options: &skills
          - UX/UI
          - UXR
          - Graphic
          - Brand
          - Frontend
          - Backend
          - Full Stack
          - AI/ML
          - Quant
          - QA
          - Game Dev
          - SRE
          - Product
          - Project
          - Program
          - CAD/Simulation
          - Manufacturing
          - Materials
          - Automotive
          - Aero
          - Embedded
          - Signals
          - Sensors
          - Robotics
          - Power Systems
          - Communications
          - Data
          - Business
          - VC
          - IDK Yet!
          - Other
      skill2:
        description: 'Secondary skill'
        required: true
        type: choice
        options: *skills
      skill3:
        description: 'Tertiary skill'
        required: true
        type: choice
        options: *skills
      bio:
        description: 'Bio (optional)'
        required: false

jobs:
  add-node:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.name "webring-bot"
          git config --global user.email "webring-bot@users.noreply.github.com"

      - name: Create branch
        id: create_branch
        run: |
          FULL_NAME="${{ github.event.inputs.fullName }}"
          # slugify: lowercase, non-alnum -> '-', trim leading/trailing '-'
          SLUG=$(printf "%s" "$FULL_NAME" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g')
          BRANCH_NAME="add/${SLUG}-${{ github.run_id }}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"
          git checkout -b "$BRANCH_NAME"

      - name: Validate data file exists
        run: |
          if [ ! -f public/data.json ]; then
            echo "Data file not found at public/data.json"
            exit 1
          fi

      - name: Append node to public/data.json
        id: append
        run: |
          FULL_NAME="${{ github.event.inputs.fullName }}"
          YEAR="${{ github.event.inputs.year }}"
          WEBSITE="${{ github.event.inputs.website }}"
          SKILL1="${{ github.event.inputs.skill1 }}"
          SKILL2="${{ github.event.inputs.skill2 }}"
          SKILL3="${{ github.event.inputs.skill3 }}"
          BIO="${{ github.event.inputs.bio }}"

          # Compute next id = (max existing id) + 1, or 1 if none
          NEXT_ID=$(jq '[.nodes[].id] | (max? // 0) + 1' public/data.json)

          # Build new node JSON
          NEW_NODE=$(jq -n \
            --argjson id "$NEXT_ID" \
            --arg fullName "$FULL_NAME" \
            --arg year "$YEAR" \
            --arg website "$WEBSITE" \
            --arg skill1 "$SKILL1" \
            --arg skill2 "$SKILL2" \
            --arg skill3 "$SKILL3" \
            --arg bio "${BIO:-}" \
            '{
              id: $id,
              fullName: $fullName,
              year: ($year|tonumber),
              website: ($website|tostring),
              skills: { skill1: $skill1, skill2: $skill2, skill3: $skill3 },
              bio: $bio
            }')

          # Append to public/data.json (preserving other keys like links, etc.)
          TMP=$(mktemp)
          jq --argjson newNode "$NEW_NODE" '.nodes += [$newNode]' public/data.json > "$TMP"
          mv "$TMP" public/data.json

          # Expose for later steps
          echo "new_node_json<<EOF" >> $GITHUB_OUTPUT
          echo "$NEW_NODE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "next_id=$NEXT_ID" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git add public/data.json
          git commit -m "feat: add ${{ github.event.inputs.fullName }} (${{ github.event.inputs.year }}) [id ${{ steps.append.outputs.next_id }}]"
          git push origin "$BRANCH_NAME"
      - name: Create Pull Request
      
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Add ${{ github.event.inputs.fullName }} (${{ github.event.inputs.year }})"
          body: |
            Auto-generated from manual workflow_dispatch.

            **New node:**
            ```json
            ${{ steps.append.outputs.new_node_json }}
            ```
          base: main
          head: ${{ env.BRANCH_NAME }}
